"""Add rewrite state fields to sessions

Revision ID: 2261da49fe2f
Revises: 
Create Date: 2026-01-26 15:22:24.922139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2261da49fe2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_rewriting', sa.Boolean(), nullable=True))
    op.add_column('sessions', sa.Column('rewrite_attempt', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('rewrite_task_id', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('rewrite_task_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'rewrite_task_type')
    op.drop_column('sessions', 'rewrite_task_id')
    op.drop_column('sessions', 'rewrite_attempt')
    op.drop_column('sessions', 'is_rewriting')
    # ### end Alembic commands ###
